
# This file is automatically generated, you probably don't want to edit this

ssMPOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ssMPOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            tipo = "media",
            precision_OM = 1,
            S = 1,
            level_OM = 0.95,
            precision_OP = 0.05,
            P = 0.5,
            level_OP = 0.95,
            power_IP = 0.85,
            level_IP = 0.95,
            diff_IP = 0.05,
            P1 = 0.5,
            P2 = 0.6,
            level_IM = 0.95,
            power_IM = 0.85,
            diff_IM = 1,
            S1 = 1,
            S2 = 1,
            level_IMSC = 0.95,
            power_IMSC = 0.85,
            diff_IMSC = 1,
            SC = 1, ...) {

            super$initialize(
                package="ssMP",
                name="ssMP",
                requiresData=FALSE,
                ...)

            private$..tipo <- jmvcore::OptionList$new(
                "tipo",
                tipo,
                options=list(
                    "media",
                    "proporcion",
                    "dosMediasVD",
                    "dosMediasVC",
                    "dosProporciones"),
                default="media")
            private$..precision_OM <- jmvcore::OptionNumber$new(
                "precision_OM",
                precision_OM,
                default=1,
                min=0.0001)
            private$..S <- jmvcore::OptionNumber$new(
                "S",
                S,
                default=1)
            private$..level_OM <- jmvcore::OptionNumber$new(
                "level_OM",
                level_OM,
                default=0.95,
                min=0.0001,
                max=0.9999)
            private$..precision_OP <- jmvcore::OptionNumber$new(
                "precision_OP",
                precision_OP,
                default=0.05,
                min=0.0001,
                max=0.9999)
            private$..P <- jmvcore::OptionNumber$new(
                "P",
                P,
                default=0.5,
                min=0.0001,
                max=1)
            private$..level_OP <- jmvcore::OptionNumber$new(
                "level_OP",
                level_OP,
                default=0.95,
                min=0.0001,
                max=0.9999)
            private$..power_IP <- jmvcore::OptionNumber$new(
                "power_IP",
                power_IP,
                default=0.85,
                min=0.0001,
                max=0.9999)
            private$..level_IP <- jmvcore::OptionNumber$new(
                "level_IP",
                level_IP,
                default=0.95,
                min=0.0001,
                max=0.9999)
            private$..diff_IP <- jmvcore::OptionNumber$new(
                "diff_IP",
                diff_IP,
                default=0.05,
                min=0.0001,
                max=0.9999)
            private$..P1 <- jmvcore::OptionNumber$new(
                "P1",
                P1,
                default=0.5,
                min=0.0001,
                max=1)
            private$..P2 <- jmvcore::OptionNumber$new(
                "P2",
                P2,
                default=0.6,
                min=0.0001,
                max=1)
            private$..level_IM <- jmvcore::OptionNumber$new(
                "level_IM",
                level_IM,
                default=0.95,
                min=0.0001,
                max=0.9999)
            private$..power_IM <- jmvcore::OptionNumber$new(
                "power_IM",
                power_IM,
                default=0.85,
                min=0.0001,
                max=0.9999)
            private$..diff_IM <- jmvcore::OptionNumber$new(
                "diff_IM",
                diff_IM,
                default=1,
                min=0.0001)
            private$..S1 <- jmvcore::OptionNumber$new(
                "S1",
                S1,
                default=1)
            private$..S2 <- jmvcore::OptionNumber$new(
                "S2",
                S2,
                default=1)
            private$..level_IMSC <- jmvcore::OptionNumber$new(
                "level_IMSC",
                level_IMSC,
                default=0.95,
                min=0.0001,
                max=0.9999)
            private$..power_IMSC <- jmvcore::OptionNumber$new(
                "power_IMSC",
                power_IMSC,
                default=0.85,
                min=0.0001,
                max=0.9999)
            private$..diff_IMSC <- jmvcore::OptionNumber$new(
                "diff_IMSC",
                diff_IMSC,
                default=1,
                min=0.0001)
            private$..SC <- jmvcore::OptionNumber$new(
                "SC",
                SC,
                default=1)

            self$.addOption(private$..tipo)
            self$.addOption(private$..precision_OM)
            self$.addOption(private$..S)
            self$.addOption(private$..level_OM)
            self$.addOption(private$..precision_OP)
            self$.addOption(private$..P)
            self$.addOption(private$..level_OP)
            self$.addOption(private$..power_IP)
            self$.addOption(private$..level_IP)
            self$.addOption(private$..diff_IP)
            self$.addOption(private$..P1)
            self$.addOption(private$..P2)
            self$.addOption(private$..level_IM)
            self$.addOption(private$..power_IM)
            self$.addOption(private$..diff_IM)
            self$.addOption(private$..S1)
            self$.addOption(private$..S2)
            self$.addOption(private$..level_IMSC)
            self$.addOption(private$..power_IMSC)
            self$.addOption(private$..diff_IMSC)
            self$.addOption(private$..SC)
        }),
    active = list(
        tipo = function() private$..tipo$value,
        precision_OM = function() private$..precision_OM$value,
        S = function() private$..S$value,
        level_OM = function() private$..level_OM$value,
        precision_OP = function() private$..precision_OP$value,
        P = function() private$..P$value,
        level_OP = function() private$..level_OP$value,
        power_IP = function() private$..power_IP$value,
        level_IP = function() private$..level_IP$value,
        diff_IP = function() private$..diff_IP$value,
        P1 = function() private$..P1$value,
        P2 = function() private$..P2$value,
        level_IM = function() private$..level_IM$value,
        power_IM = function() private$..power_IM$value,
        diff_IM = function() private$..diff_IM$value,
        S1 = function() private$..S1$value,
        S2 = function() private$..S2$value,
        level_IMSC = function() private$..level_IMSC$value,
        power_IMSC = function() private$..power_IMSC$value,
        diff_IMSC = function() private$..diff_IMSC$value,
        SC = function() private$..SC$value),
    private = list(
        ..tipo = NA,
        ..precision_OM = NA,
        ..S = NA,
        ..level_OM = NA,
        ..precision_OP = NA,
        ..P = NA,
        ..level_OP = NA,
        ..power_IP = NA,
        ..level_IP = NA,
        ..diff_IP = NA,
        ..P1 = NA,
        ..P2 = NA,
        ..level_IM = NA,
        ..power_IM = NA,
        ..diff_IM = NA,
        ..S1 = NA,
        ..S2 = NA,
        ..level_IMSC = NA,
        ..power_IMSC = NA,
        ..diff_IMSC = NA,
        ..SC = NA)
)

ssMPResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ssMPResults",
    inherit = jmvcore::Group,
    active = list(
        tableOM = function() private$.items[["tableOM"]],
        tableOP = function() private$.items[["tableOP"]],
        tableIM = function() private$.items[["tableIM"]],
        tablePM = function() private$.items[["tablePM"]],
        tableIP = function() private$.items[["tableIP"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sample Size Results")
            self$add(jmvcore::Table$new(
                options=options,
                name="tableOM",
                title="Sample Size for One-Sample Mean. Infinite population.",
                visible="(tipo == 'media')",
                rows=5,
                columns=list(
                    list(
                        `name`="parameter", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tableOP",
                title="Sample Size for One-Sample Proportion (Normal aprox.). Infinite population.",
                visible="(tipo == 'proporcion')",
                rows=5,
                columns=list(
                    list(
                        `name`="parameter", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tableIM",
                title="Sample Size for Two Independent Means different variance (Welch)",
                visible="(tipo == 'dosMediasVD')",
                rows=10,
                columns=list(
                    list(
                        `name`="parameter", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tablePM",
                title="Sample Size for Two Independent Means common variance (Pooled)",
                visible="(tipo == 'dosMediasVC')",
                rows=9,
                columns=list(
                    list(
                        `name`="parameter", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tableIP",
                title="Sample Size for Two Independent Proportions",
                visible="(tipo == 'dosProporciones')",
                rows=10,
                columns=list(
                    list(
                        `name`="parameter", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))}))

ssMPBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ssMPBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ssMP",
                name = "ssMP",
                version = c(1,0,0),
                options = options,
                results = ssMPResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Sample Size Calculator
#'
#' 
#' @param tipo .
#' @param precision_OM .
#' @param S .
#' @param level_OM .
#' @param precision_OP .
#' @param P .
#' @param level_OP .
#' @param power_IP .
#' @param level_IP .
#' @param diff_IP .
#' @param P1 .
#' @param P2 .
#' @param level_IM .
#' @param power_IM .
#' @param diff_IM .
#' @param S1 .
#' @param S2 .
#' @param level_IMSC .
#' @param power_IMSC .
#' @param diff_IMSC .
#' @param SC .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$tableOM} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tableOP} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tableIM} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tablePM} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tableIP} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$tableOM$asDF}
#'
#' \code{as.data.frame(results$tableOM)}
#'
#' @export
ssMP <- function(
    tipo = "media",
    precision_OM = 1,
    S = 1,
    level_OM = 0.95,
    precision_OP = 0.05,
    P = 0.5,
    level_OP = 0.95,
    power_IP = 0.85,
    level_IP = 0.95,
    diff_IP = 0.05,
    P1 = 0.5,
    P2 = 0.6,
    level_IM = 0.95,
    power_IM = 0.85,
    diff_IM = 1,
    S1 = 1,
    S2 = 1,
    level_IMSC = 0.95,
    power_IMSC = 0.85,
    diff_IMSC = 1,
    SC = 1) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ssMP requires jmvcore to be installed (restart may be required)")


    options <- ssMPOptions$new(
        tipo = tipo,
        precision_OM = precision_OM,
        S = S,
        level_OM = level_OM,
        precision_OP = precision_OP,
        P = P,
        level_OP = level_OP,
        power_IP = power_IP,
        level_IP = level_IP,
        diff_IP = diff_IP,
        P1 = P1,
        P2 = P2,
        level_IM = level_IM,
        power_IM = power_IM,
        diff_IM = diff_IM,
        S1 = S1,
        S2 = S2,
        level_IMSC = level_IMSC,
        power_IMSC = power_IMSC,
        diff_IMSC = diff_IMSC,
        SC = SC)

    analysis <- ssMPClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

